name: Deploy to EKS

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-aws-region
      
      - name: Install kubectl
        run: |
         sudo apt-get update
         sudo apt-get install -y kubectl

      - name: Deploy to EKS
        run: kubectl apply -f Task_3/deployment.yaml
